Stat svc
den4ikos/java-explore-with-me pull request #1
Opened 2023-02-14 19:07 UTC by den4ikos

2023-02-15 19:52 UTC, krylov-sergey-sergeevich requested changes
Привет

Есть некоторые вопросы, что-то в коде отметил сразу
1) Не заметил http клиент для работы с модулем статистики
2) Что думаешь быть на счет еще одной таблицы в БД  с названием примерно apps где мы бы хранили название например и из таблицы с hit ссылались бы на app при помощи foreign key?

**Вопрос по:** "Определится с тематикой дополнительной функциональности, которую вы будете реализовывать" **какой она будет?**

Буду ждать  с правками, если что пиши в пачке =)

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/pom.xml
> +			<artifactId>xmlunit-core</artifactId>
А для чего эта зависимость?

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/annotation/IpCheckConstraint.java
> +public @interface IpCheckConstraint {
Красивое решение

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/validation/LocalDateTimeValidator.java
> +        System.out.println("AZZA");
Вероятно это должно быть удалено =)

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/config/AppConfig.java
> +    public JpaTransactionManager transactionManager(@Autowired EntityManagerFactory entityManagerFactory) {
А для чего это?

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/config/AppConfig.java
> +@EnableTransactionManagement
Это что даст в нашем случае?

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/log/LogHelper.java
> +public class LogHelper {
**Стиль:** Пустую строку между объявлением класса и методом

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/log/LogHelper.java
> +    public static void dump(Map<String, Object> params, HttpServletRequest request) {
Неплохая утилита

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/dto/HitDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
**Можно лучше:** Паттерн  "yyyy-MM-dd HH:mm:ss" лучше вынести в класс Constants

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/dto/HitDtoInterface.java
> +    Long getId();
**Стиль:** Пустую строку между объявлением класса и методом

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/mapper/HitMapper.java
> +    public static Hit toHit(HitDto hitDto) {
**Стиль:** Пустую строку между объявлением класса и методом

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/service/interfaces/StatisticServiceInterface.java
> +public interface StatisticServiceInterface {
В название класса лучше не писать его сущность те можно просто interface StatisticService

2023-02-15 19:52 UTC, krylov-sergey-sergeevich commented on statistics/src/main/resources/data.sql
> +create table hits
**Логика:** 255 везде надо поправить и сделать более продуманные значения с учетом их специфики

2023-02-16 17:14 UTC, den4ikos commented on statistics/pom.xml
> +			<artifactId>xmlunit-core</artifactId>
это я помники в нете искал, забыл наверно удалить
удалил

2023-02-16 17:14 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/annotation/IpCheckConstraint.java
> +public @interface IpCheckConstraint {
спасибо

2023-02-16 17:16 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/validation/LocalDateTimeValidator.java
> +        System.out.println("AZZA");
Да, я хотел дату валидировать, но метод не пригодился. Оставлю пока что пустым. Возможно пригодится для другого модуля

2023-02-16 17:19 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/config/AppConfig.java
> +    public JpaTransactionManager transactionManager(@Autowired EntityManagerFactory entityManagerFactory) {
Это для использования транзакций
Нам в теории давали в теме "Транзакции в Spring" 

2023-02-16 17:20 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/config/AppConfig.java
> +@EnableTransactionManagement
включает управление транзакциями и обработку соответствующих аннотаций

2023-02-16 17:23 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/dto/HitDto.java
> +    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
вынес

2023-02-16 17:26 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/service/interfaces/StatisticServiceInterface.java
> +public interface StatisticServiceInterface {
исправил

2023-02-16 17:38 UTC, den4ikos commented on statistics/src/main/resources/data.sql
> +create table hits
исправил

2023-02-16 17:38 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/mapper/HitMapper.java
> +    public static Hit toHit(HitDto hitDto) {
исправил

2023-02-16 17:38 UTC, den4ikos commented on statistics/src/main/java/ru/practicum/explorewithme/dto/HitDtoInterface.java
> +    Long getId();
исправил

2023-02-16 20:37 UTC, den4ikos commented
Http клиента добавил, но я думал реализовать это при разработке главного модуля
С базой поработал
По дополнительной фиче я выбрал подписки

2023-02-17 04:43 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

p.s оставил 1 вопрос, но он не критичен

2023-02-17 04:43 UTC, krylov-sergey-sergeevich commented on statistics/src/main/java/ru/practicum/explorewithme/validation/LocalDateTimeValidator.java
> +public class LocalDateTimeValidator implements ConstraintValidator<LocalDateTimeConstraint, String> {
А тут ничего не забыли?

2023-02-17 17:52 UTC, merged