Main svc
den4ikos/java-explore-with-me pull request #2
Opened 2023-02-26 12:22 UTC by den4ikos

2023-02-27 06:40 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но давай поправим мелочи и будет зачет

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +    title   varchar(255) default null,
Рекомендую делать пустую строку между полями и constraint так визуально лучше

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +    unique (title)
Это такой же constraint как и другие давай дадим ему название

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/client/StatisticClient.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/stats?start={start}&end={end}&uris={uris}&unique={unique}")
А тут нельзя попытаться воспользоваться GetMapping чтобы сократить код?

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/main
Можно лучше:
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/application.properties
> +spring.config.activate.on-profile=production
А это для чего осталось? И следующие 4 строки

2023-02-27 06:40 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +    unique (title)
CONSTRAINT UQ_USER_EMAIL UNIQUE (email)

2023-02-27 12:42 UTC, den4ikos commented on main-service/src/main/resources/data.sql
> +    title   varchar(255) default null,
исправил

2023-02-27 12:47 UTC, den4ikos commented on main-service/src/main/resources/data.sql
> +    unique (title)
исправил

2023-02-27 12:50 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/client/StatisticClient.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/stats?start={start}&end={end}&uris={uris}&unique={unique}")
изменил

2023-02-27 13:07 UTC, den4ikos commented on main-service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/main
исправил, но если честно, то не понял, какой в этом смысл
ведь все равно все креды в этом же файле лежат

2023-02-27 13:13 UTC, den4ikos commented on main-service/src/main/resources/application.properties
> +spring.config.activate.on-profile=production
это для работы с h2

2023-02-28 06:10 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

Отписал что еще можно доработать =)

2023-02-28 06:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +    primary key (id)
constraint {} - отсутствует

2023-02-28 06:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +    primary key (compilation_id, event_id)
constraint {} - отсутствует

2023-02-28 06:10 UTC, krylov-sergey-sergeevich commented on statistics/src/main/resources/data.sql
>      unique (name)
constraint {} - отсутствует

2023-02-28 06:10 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/main
Чтобы можно было из вне приложения их задать и переопределить, для работы например с другой бд

2023-02-28 06:26 UTC, merged