Feature subscriptions
den4ikos/java-explore-with-me pull request #3
Opened 2023-03-05 10:32 UTC by den4ikos

2023-03-06 07:03 UTC, krylov-sergey-sergeevich requested changes
Привет, все в целом неплохо, давай поправим мелочи

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on README.md
> +
Давай опишем какая функциональность была реализована

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/entity/Subscriber.java
> +    private User signatory;
Можно лучше: eventOwner

Текущее название как-то тяжеловато воспринимается

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +public class SubscriptionHelper {
Давай добавим javadoc

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +    private static boolean containsEnumStatus(String statusValue) {
Этот метод лучше в енам вынести

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +    public static SubscriberStatus convertFromString(String status) {
Это тоже лучше в енам вынести

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +create table if not exists subscribers
not null нигде не добавим?

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/resources/data.sql
> +create table if not exists subscribers
Если хочешь давай потренируемся и добавим комменты к столбцам, если есть желание

2023-03-06 07:03 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/explorewithmemain/controller/SubscribeController.java
> +public class SubscribeController {
**Учесть и поправить нейминг методов:** get - это или получение объекта или исключение, find - это или объект или null

p.s Это везде желательно поправить по пути

2023-03-06 15:56 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/entity/Subscriber.java
> +    private User signatory;
Исправил

2023-03-06 16:10 UTC, den4ikos commented on main-service/src/main/resources/data.sql
> +create table if not exists subscribers
сделал

2023-03-06 18:24 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +    private static boolean containsEnumStatus(String statusValue) {
исправил

2023-03-06 18:24 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +    public static SubscriberStatus convertFromString(String status) {
исправил

2023-03-06 18:37 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/controller/SubscribeController.java
> +public class SubscribeController {
исправил

2023-03-06 19:01 UTC, den4ikos commented on main-service/src/main/java/ru/practicum/explorewithmemain/helper/SubscriptionHelper.java
> +public class SubscriptionHelper {
добавил

2023-03-07 15:01 UTC, krylov-sergey-sergeevich approved these changes
Привет, все хорошо - зачет!

2023-03-07 17:27 UTC, merged